steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/web:${_TAG}'
      - '-f'
      - 'services/web/Dockerfile'
      - 'services/web'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/web:${_TAG}'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--command=kubectl rollout restart deployment sunriseobx-web -n sunriseobx'
      - '--cluster=sunriseobx'
      - '--location=us-central1-a'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/web:${_TAG}'
substitutions:
  _TAG: latest
timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
