steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/pkg:${_TAG}'
      - '-f'
      - 'services/pkg/Dockerfile'
      - 'services/pkg'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/pkg:${_TAG}'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sunriseobx-images/pkg:${_TAG}'
substitutions:
  _TAG: latest
timeout: 300s
