[package]
name = "sunrise-web-sys"
version = "0.1.0"
edition = "2021"
description = "WASM bindings for the SunriseOBX API client"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sunrise-common = { path = "../sunrise-common" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Headers",
    "Request",
    "RequestInit",
    "Response",
    "Window",
    "WorkerGlobalScope",
] }
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
