apiVersion: v1
kind: Service
metadata:
  name: sunriseobx-cdn
  namespace: sunriseobx
  labels:
    app: cdn
spec:
  type: ClusterIP
  selector:
    app: cdn
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
