apiVersion: v1
kind: Service
metadata:
  name: sunriseobx-api
  namespace: sunriseobx
spec:
  type: ClusterIP
  selector:
    app: sunriseobx-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
